### ISSUE TITLE
Question on the L2 smooth difference for emit learning fun

### ISSUE THREAD

**Issue by andrewsong90** [janclemenslab/pyGLMHMM#2]
Dear authors,

First of all, thank you so much for pulling off the hard work for implementing the python version of GLM-HMM.

I had a quick question (potentially an issue) with the L2 difference smoothing of the filters. (in emitLearningFun.py)
It seems the author is 1) using the difference matrix with (-1, 2, -1) on the diagonals 2) multiplying it with the filter vector 3) squaring the resulting vector and 4) summing them up.

However, if I am not mistaken, this doesn't lead to the L2 difference smoothing on the filter. Wouldn't you need to dot product  the resulting vector from 2) with the filter vector itself?

Let me know!

**Comment by postpop** [comment]
Hi Andrew, sorry about the late reply - this is probably a bug in the original matlab version. We are not maintaining this port anymore since it's quite buggy. Please use Scott Linderman's [ssm](https://github.com/lindermanlab/ssm) package to fit HMM-GLM type model. This [notebook](https://github.com/lindermanlab/ssm/blob/master/notebooks/2b%20Input%20Driven%20Observations%20(GLM-HMM).ipynb) from the ssm package is a great starting point.
